# Assignment 3 by Payal Mahajan, Batch - 1, Data Science Essentials, LetsUpgrade

# Ques 1: Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np

In [4]:
np.arange(start=2, stop=51, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Ques 2: Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [6]:

l = input("Enter a list of 5 elements ")
m = input("Enter a list of 5 elements ")
print("\n")
userList1 = l.split()
print("user list is ", userList1)
userlist2 = m.split()
print("user list 2 is ", userlist2)
array1 = np.array(userList1)
array2 = np.array(userlist2)
print("\n")
arr = np.concatenate((array1, array2))
print("After concatenation array is", arr)
print("\n")
print("After sorting, array becomes")
print(np.sort(arr, axis = 0))

Enter a list of 5 elements 1 2 3 4 5
Enter a list of 5 elements 6 7 8 9 99


user list is  ['1', '2', '3', '4', '5']
user list 2 is  ['6', '7', '8', '9', '99']


After concatenation array is ['1' '2' '3' '4' '5' '6' '7' '8' '9' '99']


After sorting, array becomes
['1' '2' '3' '4' '5' '6' '7' '8' '9' '99']


# Ques 3: Write a code snippet to find the dimensions of a ndarray and its size.

In [10]:
arr = np.array([4, 5, 6, 7, 8, 9, 10, 11])
print('Dimension of 1D numpy array : ', arr.shape)
arr1 = np.size(arr, axis=None)
print("Size of array is", arr1)

Dimension of 1D numpy array :  (8,)
Size of array is 8


# Ques 4: How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet        Hint: np.newaxis, np.expand_dims

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [15]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

# Ques 5: Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()

In [17]:
f = np.array([1,2,3,7])
g = np.array([4,5,6,8])
print('Vertical Append: \n', np.vstack((f, g)))
hori = np.hstack((f,g)) 
print("Horizontal Append", hori)

Vertical Append: 
 [[1 2 3 7]
 [4 5 6 8]]
Horizontal Append [1 2 3 7 4 5 6 8]


# Ques 6: How to get unique items and counts of unique items?

In [22]:
a = np.array( [10,10,20,10,20,20,20,30,30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("\n Counts of unique values of the array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]

 Counts of unique values of the array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
